"""
Django settings for Main project.

Generated by 'django-admin startproject' using Django 1.8.13.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '3q@l-43sxi=436k3+xi7m-p2ivqz&ptvkm)vg2pr!ji$9qev2z'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'books',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'Main.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # First DIRS working, but Second DIRS AND Thirds DIRS not working
        # And Last DIRS working
        # 'DIRS': [os.path.join(os.path.dirname(__file__), 'Templates').replace('\\', '/'), ],
        # 'DIRS': [os.path.dirname(os.path.dirname(os.path.abspath(__file__)))],
        # 'DIRS': [os.path.join(BASE_DIR, 'Main/Templates')],
        'DIRS': [
            'E:/Django/Django_Template_1_2/MyDjango_Template_1_2/My_Django_Template_1_2/Main',
            '/Templates',
            'E:/Django/Django_Template_1_2/MyDjango_Template_1_2/My_Django_Template_1_2/books',
            '/Templates',
         ],
        # 'DIRS': [
        #      'E:/Django/Django_Template_1_2/MyDjango_Template_1_2/My_Django_Template_1_2/Main'
        #      '/Templates',
        #  ],
        #      'E:/Django/Django_Template_1_2/MyDjango_Template_1_2/My_Django_Template_1_2/Main'
        #      '/Templates/current_datetime.html',
        #      'E:/Django/Django_Template_1_2/MyDjango_Template_1_2/My_Django_Template_1_2/Main'
        #      '/Templates/template1.html',
        #      'E:/Django/Django_Template_1_2/MyDjango_Template_1_2/My_Django_Template_1_2/Main'
        #      '/Templates/template2.html',
        #      # 'E:/Django/Django_Template_1_2/MyDjango_Template_1_2/My_Django_Template_1_2/Main'
        #      # '/Templates',
        #      # 'E:/Django/Django_Template_1_2/MyDjango_Template_1_2/My_Django_Template_1_2/Main'
        #      # '/Templates/mypage.html'
        # ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Main.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'
# STATICFILES_DIRS = [
# os.path.join(BASE_DIR, 'Main', 'static'),
# ]

# STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
